export const LOAIXE_SET = "LOAIXE_SET";
export const LOAIXE_EDIT = "LOAIXE_EDIT";
export const LOAIXES_SET = "LOAIXES_SET";
export const LOAIXES_DELETE = "LOAIXES_DELETE";
export const LOAIXES_STATE_CLEAR = "LOAIXES_STATE_CLEAR";

export const MANUFACTURER_SET = "MANUFACTURER_SET";
export const MANUFACTURER_APPEND = "MANUFACTURER_APPEND";
export const MANUFACTURER_UPDATE = "MANUFACTURER_UPDATE";
export const MANUFACTURERES_SET = "MANUFACTURERES_SET";
export const MANUFACTURERES_DELETE = "MANUFACTURERES_DELETE";
export const MANUFACTURERES_STATE_CLEAR = "MANUFACTURERES_STATE_CLEAR";

export const CAR_SET = "CAR_SET";
export const CAR_ADDEND = "CAR_ADDEND";
export const CARS_SET = "CARS_SET";
export const CARS_DEL = "CARS_DEL";

export const ACCOUNT_SET = "ACCOUNT_SET";
export const ACCOUNT_ADDEND = "ACCOUNT_ADDEND";
export const ACCOUNTS_SET = "ACCOUNTS_SET";
export const ACCOUNTS_DEL = "ACCOUNTS_DEL";
export const ACCOUNT_STATE_CLEAR = "ACCOUNT_STATE_CLEAR";

export const ORDERS_SET = "ORDERS_SET";
export const ORDERSDETAIL_SET = "ORDERSDETAIL_SET";
export const ORDERS_DEL = "ORDERS_DEL";
export const ORDER_STATE_CLEAR = "ORDER_STATE_CLEAR";

export const COMMON_LOADING_SET = "COMMON_LOADING_SET";

export const NHANVIEN_SET = "NHANVIEN_SET";
export const NHANVIEN_ADDEND = "NHANVIEN_ADDEND";
export const NHANVIENS_SET = "NHANVIENS_SET";
export const NHANVIENS_DEL = "NHANVIENS_DEL";
export const NHANVIENS_STATE_CLEAR = "NHANVIENS_STATE_CLEAR";

export const TUYENXE_SET = "TUYENXE_SET";
export const TUYENXE_APPEND = "TUYENXE_APPEND";
export const TUYENXE_UPDATE = "TUYENXE_UPDATE";
export const TUYENXES_SET = "TUYENXES_SET";
export const TUYENXES_DELETE = "TUYENXES_DELETE";
export const TUYENXES_STATE_CLEAR = "TUYENXES_STATE_CLEAR";

export const CHUYEN_SET = "CHUYEN_SET";
export const CHUYEN_EDIT = "CHUYEN_EDIT";
export const CHUYEN_UPDATE = "CHUYEN_UPDATE";
export const CHUYENS_SET = "CHUYENS_SET";
export const CHUYEN_APPEND = "CHUYEN_APPEND";
export const CHUYENS_DELETE = "CHUYENS_DELETE";
export const CHUYENS_STATE_CLEAR = "CHUYENS_STATE_CLEAR";
