export const CATEGORY_SET = "CATEGORY_SET";
export const CATEGORY_EDIT = "CATEGORY_EDIT";
export const CATEGORIES_SET = "CATEGORIES_SET";
export const CATEGORIES_DELETE = "CATEGORIES_DELETE";
export const CATEGORIES_STATE_CLEAR = "CATEGORIES_STATE_CLEAR";

export const MANUFACTURER_SET = "MANUFACTURER_SET";
export const MANUFACTURER_APPEND = "MANUFACTURER_APPEND";
export const MANUFACTURER_UPDATE = "MANUFACTURER_UPDATE";
export const MANUFACTURERES_SET = "MANUFACTURERES_SET";
export const MANUFACTURERES_DELETE = "MANUFACTURERES_DELETE";
export const MANUFACTURERES_STATE_CLEAR = "MANUFACTURERES_STATE_CLEAR";

export const PRODUCT_SET = "PRODUCT_SET";
export const PRODUCT_ADDEND = "PRODUCT_ADDEND";
export const PRODUCTS_SET = "PRODUCTS_SET";
export const PRODUCTS_DEL = "PRODUCTS_DEL";

export const ACCOUNT_SET = "ACCOUNT_SET";
export const ACCOUNT_ADDEND = "ACCOUNT_ADDEND";
export const ACCOUNTS_SET = "ACCOUNTS_SET";
export const ACCOUNTS_DEL = "ACCOUNTS_DEL";
export const ACCOUNT_STATE_CLEAR = "ACCOUNT_STATE_CLEAR";

export const ORDERS_SET = "ORDERS_SET";
export const ORDERSDETAIL_SET = "ORDERSDETAIL_SET";
export const ORDERS_DEL = "ORDERS_DEL";
export const ORDER_STATE_CLEAR = "ORDER_STATE_CLEAR";

export const COMMON_LOADING_SET = "COMMON_LOADING_SET";
